import type { Metadata } from 'next'
import './globals.css'

import localFont from 'next/font/local'

const myFont = localFont({
  src: './fonts/UKIJTuz.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ug" dir="rtl">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
