import type { Metadata } from 'next'
import './globals.css'
import { ukijtuz } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ug" dir="rtl">
      <body className={ukijtuz.className}>{children}</body>
    </html>
  )
}
